config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'profile/show'
  resources :replies
  resources :categories
  resources :votes do
    member do
      get :like, to: 'votes#like', as: :like
      get :dislike, to: 'votes#dislike', as: :dislike
    end
  end
  resources :discussions do
    collection do
      get :search, to: 'discussions#search', as: :search
      get :popular, to: 'discussions#popular', as: :popular
      get :most_upvoted, to: 'discussions#most_upvoted', as: :most_upvoted
    end
    member do
      post :vote, to: 'discussions#vote'
      resources :arguments
    end
  end

  root 'discussions#index'
  devise_for :users
  resources :users
  get :user, to: 'users#profile', as: :profile
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/reply.rb
# frozen_string_literal: true

class Reply < ApplicationRecord
  belongs_to :argument
  belongs_to :user
  has_many :votes, as: :item

  validates :content, presence: true
end

app/controllers/replies_controller.rb
# frozen_string_literal: true

class RepliesController < ApplicationController
  before_action :set_reply, only: %i[show update destroy]
  before_action :authenticate_user!

  # GET /replies/new
  def new
    @argument_id = params[:argument_id]
    @reply = Reply.new
  end

  # GET /replies/1/edit
  def edit
    @reply = Reply.find(params[:reply_id])
  end

  # POST /replies
  # POST /replies.json
  def create
    @reply = Reply.new(params[:reply].permit(:content, :argument_id))
    @reply.user_id = current_user.id

    respond_to do |format|
      if @reply.save
        format.html { redirect_to @reply.argument.discussion, notice: 'Reply was successfully created.' }
        format.json { render :show, status: :created, location: @reply }
      else
        format.html { redirect_to @reply.argument.discussion, notice: 'Ouch! Some problem here' }
        format.json { render json: @reply.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /replies/1
  # PATCH/PUT /replies/1.json
  def update
    respond_to do |format|
      if EditPolicy.reply_can_be_edited?(@reply, current_user) && @reply.update_attributes(params[:reply].permit(:content))
        format.html { redirect_to @reply.argument.discussion, notice: 'Reply was successfully updated.' }
        format.json { render :show, status: :ok, location: @reply }
      else
        format.html { redirect_to @reply.argument.discussion, alert: 'You dont have permition!' }
        format.json { render json: @reply.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /replies/1
  # DELETE /replies/1.json
  def destroy
    respond_to do |format|
      if current_user.has_role?(:admin) && @reply.destroy
        format.html { redirect_to @reply.argument.discussion, notice: 'Reply was successfully destroyed.' }
      else
        format.html { redirect_to @reply.argument.discussion, alert: 'You dont have permition!' }
        format.json { head :no_content }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_reply
    @reply = Reply.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def reply_params
    params.require(:reply).permit(:reply)
  end
end

app/helpers/replies_helper.rb
# frozen_string_literal: true

module RepliesHelper
end

app/views/replies/_form.html.erb
<%= simple_form_for(reply) do |f| %>
<%= f.hidden_field :argument_id, value: @argument_id %>
<article class="media">
  <figure class="media-left">
    <p class="image is-48x48">
      <%= image_tag(current_user.avatar.url(:thumb), class: 'border-radius-50', size: 48, alt: current_user.username) %>
    </p>
  </figure>
  <div class="media-content">
    <div class="field">
      <p class="control">
        <%= f.input :content, input_html: { class: 'textarea', rows: '5', placeholder: "Add some text..."}, wrapper: false, label_html: { class: 'label' }, label: false %>
      </p>
    </div>
    <nav class="level">
      <div class="level-left">
        <div class="level-item">
          <%= f.button :submit, class:'button is-success is-active' %>
        </div>
      </div>
    </nav>
  </div>
</article>

<% end %>



 

app/views/replies/_reply.html.erb
  <article class="media">
    <div class="media-left">
      <figure class="image is-48x48">
        <%= image_tag(reply.user.avatar.url(:thumb), class: 'border-radius-50', size: 48, alt: reply.user.username) %>
      </figure>
    </div>
    <% if reply.user.side(reply.argument.discussion.id) == 'left' %>
    <div class="media-content">
      <div class="content">
        <article class="message is-link">
        <div class="message-body">
        <p>
          <strong><%= reply.user.username %></strong> <small>posted <%= time_ago_in_words(reply.created_at) %> ago</small>
          <br>
          <div class="overflow-wrap">
          <%= reply.content %>
          </div>
        </p>
       </div>
       </article>
        </div>
       <nav class="level is-mobile">
        <div class="level-left">
         <a class="level-item" aria-label="like">
            <%= link_to like_vote_path(item_id: reply.id, item_type: 'Reply') do %>
            <span class="icon is-small">
              <i class="fa fa-thumbs-up" aria-hidden="true"><%= VotesWorker.get_likes(reply.id, 'Reply') %></i>
            </span>
            <% end %>
          </a>
          <a class="level-item" aria-label="dislike">
            <%= link_to dislike_vote_path(item_id: reply.id, item_type: 'Reply') do %>
            <span class="icon is-small">
              <i class="fa fa-thumbs-down" aria-hidden="true"><%= VotesWorker.get_dislikes(reply.id, 'Reply') %></i>
            </span>
            <% end %>
          </a>
          <% if user_signed_in? %>          
            <% if EditPolicy.reply_can_be_edited?(reply, current_user) %>
            <a class="level-item" aria-label="edit">
            <%= link_to edit_reply_path(reply_id: reply) do %>
            <span class="icon is-small">
              <i class="fa fa-edit" aria-hidden="true"></i>
            </span>
            <% end %>
            </a>
            <% end %>
            <% if has_role?(:admin) %>
            <a class="level-item" aria-label="delete">
          <%= link_to reply, method: :delete, data: { confirm: 'Are you sure?' } do %>
            <span class="icon is-small">
              <i class="fa fa-trash-o" aria-hidden="true"></i>
            </span>
            <% end %>
            <% end %>
          </a>
          <% end %>
        </div>
      </nav>
    </div>
    <% end %>

    <% if reply.user.side(reply.argument.discussion.id) == 'right' %>
    <div class="media-content">
      <div class="content">
        <article class="message is-danger">
        <div class="message-body">
        <p>
          <strong><%= reply.user.username %></strong> <small>posted <%= time_ago_in_words(reply.created_at) %> ago</small>
          <br>
          <div class="overflow-wrap">
          <%= reply.content %>
          </div>
        </p>
       </div>
       </article>
      </div>
       <nav class="level is-mobile">
        <div class="level-left">
         <a class="level-item" aria-label="like">
            <%= link_to like_vote_path(item_id: reply.id, item_type: 'Reply') do %>
            <span class="icon is-small">
              <i class="fa fa-thumbs-up" aria-hidden="true" style="color:red"><%= VotesWorker.get_likes(reply.id, 'Reply') %></i>
            </span>
            <% end %>
          </a>
          <a class="level-item" aria-label="dislike">
            <%= link_to dislike_vote_path(item_id: reply.id, item_type: 'Reply') do %>
            <span class="icon is-small">
              <i class="fa fa-thumbs-down" aria-hidden="true" style="color:red"></i>
            </span>
            <% end %>
          </a>
          <% if user_signed_in? %>          
            <% if EditPolicy.reply_can_be_edited?(reply, current_user) %>
            <a class="level-item" aria-label="edit">
            <%= link_to edit_reply_path(reply_id: reply) do %>
            <span class="icon is-small">
              <i class="fa fa-edit" aria-hidden="true" style="color:red"><%= VotesWorker.get_dislikes(reply.id, 'Reply') %></i>
            </span>
            <% end %>
            </a>
            <% end %>
            <% if has_role?(:admin) %>
            <a class="level-item" aria-label="delete">
          <%= link_to reply, method: :delete, data: { confirm: 'Are you sure?' } do %>
            <span class="icon is-small">
              <i class="fa fa-trash-o" aria-hidden="true" style="color:red"></i>
            </span>
            <% end %>
            <% end %>
          </a>
          <% end %>
        </div>
      </nav>
    </div>
    <% end %>
  </article>

app/views/replies/edit.html.erb
<h1 class="title">Editing Reply</h1>

<%= render 'form', reply: @reply %>

app/views/replies/new.html.erb
<h1 class="title">New Reply</h1>

<%= render 'form', reply: @reply %>
 