config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'profile/show'
  resources :replies
  resources :categories
  resources :votes do
    member do
      get :like, to: 'votes#like', as: :like
      get :dislike, to: 'votes#dislike', as: :dislike
    end
  end
  resources :discussions do
    collection do
      get :search, to: 'discussions#search', as: :search
      get :popular, to: 'discussions#popular', as: :popular
      get :most_upvoted, to: 'discussions#most_upvoted', as: :most_upvoted
    end
    member do
      post :vote, to: 'discussions#vote'
      resources :arguments
    end
  end

  root 'discussions#index'
  devise_for :users
  resources :users
  get :user, to: 'users#profile', as: :profile
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/discussion.rb
# frozen_string_literal: true

class Discussion < ApplicationRecord
  belongs_to :category
  belongs_to :user
  has_many   :arguments, dependent: :destroy
  has_many :votes, as: :item

  validates :left_side, :right_side, presence: true
  validates :left_side, :right_side, length: { in: 1..80 }
  validates :question, length: { in: 0..120 }

  def self.side_inc(id, side)
    discussion = Discussion.find(id)
    discussion.increment!("#{side}_counter")
  end

  def self.search(search)
    if search
      where(['right_side LIKE ?', search]).or(Discussion.where(['left_side LIKE ?', search])).or(Discussion.where(['question LIKE ?', search]))
    else
      find(:all)
    end
  end
  resourcify
end

app/controllers/discussions_controller.rb
# frozen_string_literal: true

class DiscussionsController < ApplicationController
  before_action :set_discussion, only: %i[show edit update destroy vote]
  before_action :authenticate_user!, except: %i[index show popular most_upvoted]

  # GET /discussions
  # GET /discussions.json
  def index
    @discussions = Discussion.all.order('created_at desc').page params[:page]
  end

  def popular
    # This better to be a column in Discussion if your base is big
    @discussions = Discussion.all.sort_by { |m| m.arguments.count }.reverse
    @discussions = Kaminari.paginate_array(@discussions).page(params[:page]).per(10)
  end

  def most_upvoted
    # This better to be a column in Discussion if your base is big
    @discussions = Discussion.all.sort_by { |m| m.votes.sum(:value) }.reverse
    @discussions = Kaminari.paginate_array(@discussions).page(params[:page]).per(10)
  end

  # GET /discussions/1
  # GET /discussions/1.json
  def show
    @discussions = Discussion.all.order('created_at desc')
  end

  # GET /discussions/new
  def new
    @discussion = current_user.discussions.build
    @categories = Category.all
  end

  # GET /discussions/1/edit
  def edit
    @categories = Category.all
  end

  # POST /discussions
  # POST /discussions.json
  def create
    @discussion = current_user.discussions.build(discussion_params)
    respond_to do |format|
      if @discussion.save
        format.html { redirect_to @discussion, notice: 'Discussion was successfully created.' }
        format.json { render :show, status: :created, location: @discussion }
      else
        @categories = Category.all
        format.html { render :new, categories: @categories }
        format.json { render json: @discussion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /discussions/1
  # PATCH/PUT /discussions/1.json
  def update
    respond_to do |format|
      if (EditPolicy.discussion_can_be_edited?(@discussion, current_user) || current_user.has_role?(:admin)) && @discussion.update(discussion_params)
        format.html { redirect_to @discussion, notice: 'Discussion was successfully updated.' }
        format.json { render :show, status: :ok, location: @discussion }
      else
        format.html { redirect_to @discussion, notice: 'You dont have permition!' }
        format.json { render json: @discussion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /discussions/1
  # DELETE /discussions/1.json
  def destroy
    respond_to do |format|
      if (EditPolicy.discussion_can_be_edited?(@discussion, current_user) || current_user.has_role?(:admin)) && @discussion.destroy
        format.html { redirect_to discussions_url, notice: 'Discussion was successfully destroyed.' }
      else
        format.html { redirect_to discussions_url, alert: 'You dont have permition!' }
        format.json { head :no_content }
      end
    end
  end

  # POST /discussions/1/vote
  def vote
    respond_to do |format|
      if DiscussionsMembersWorker.create(@discussion.id, current_user.id, params[:side])
        format.html { redirect_to @discussion, notice: 'You vote successfully.' }
        format.json { render :show, status: :ok, location: @discussion }
      else
        format.html { render :show }
        format.json { render json: @discussion.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /discussions/search
  def search
    @discussions = Discussion.search(params[:search])
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_discussion
    @discussion = Discussion.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def discussion_params
    params.require(:discussion).permit(:left_side, :right_side, :question, :category_id, :side)
  end
end

app/helpers/discussions_helper.rb
# frozen_string_literal: true

module DiscussionsHelper
  def discussion_author(discussion)
    user_signed_in? && current_user.id == discussion.user_id
  end

  def reply_author(reply)
    user_signed_in? && current_user.id == reply.user_id
  end
end

app/views/discussions/_form.html.erb
<%= simple_form_for(@discussion) do |f| %>
  <%= f.error_notification %>

  <div class="field">
    <div class="control">
      <%= f.input :left_side, required: true, input_html: { class: 'input' }, wrapper: false, label_html: { class: "label" } %>
    </div>
  </div>

  <div class="field">
    <div class="control">
      <%= f.input :right_side, required: true, input_html: { class: 'input' }, wrapper: false, label_html: { class: "label" } %>
    </div>
  </div>

  <div class="field">
    <div class="control">
      <%= f.input :question, input_html: { class: 'input' }, wrapper: false, label_html: { class: "label" } %>
    </div>
  </div>

  <div class="field">
    <label class="label">Category</label>
    <div class="control has-icons-left">
      <span class="select">
        <%= f.input_field :category_id, collection:@categories.map { |c| [c.title, c.id] }, prompt: "Select category" %>
      </span>
      <span class="icon is-small is-left">
        <i class="fa fa-tag"></i>
      </span>
    </div>
  </div>

  <div class="field">
    <div class="control">
      <%= f.button :submit, class:"button is-success is-active" %>
    </div>
  </div>

<% end %>

app/views/discussions/_form.html.haml
= form_with(model: discussion, local: true) do |form|
  - if discussion.errors.any?
    #error_explanation
      %h2
        = pluralize(discussion.errors.count, "error")
        prohibited this discussion from being saved:
      %ul
        - category.errors.full_messages.each do |message|
          %li= message
  .field
    = form.label :question
    = form.text_field :question
  .field
    = form.label :left_side
    = form.text_field :left_side
  .field
    = form.label :right_side
    = form.text_field :right_side
  .field
    = form.label :category_id
    = form.text_field :category_id
  .actions
    = form.submit

app/views/discussions/_search_form.html.erb
<%= form_tag(search_discussions_path, :method => 'get') do %>
  <nav class="level">
  <!-- Left side -->
  <div class="level-left">
    <div class="level-item">
      <div class="field has-addons">
        <p class="control">
         <%= text_field_tag :search, params[:search], class: 'input', type: 'text', placeholder: 'Find a discussion', wrapper: false %>
        </p>
        <p class="control">
          <%= submit_tag "Search", :name => nil, class:"button" %>
        </p>
      </div>
    </div>
  </div>
</nav>
<% end %>

app/views/discussions/_sidebar.html.erb
<div class="column is-3 is-offset-1">
  <h3 class="title is-5 has-text-grey-light">Categories</h3>

  <ul class="list">
   <% @categories = Category.all %>
   <% @categories.each do |c| %>
    <li><%= link_to c.title, c %>
    <% if has_role?(:admin) %>
    <%= link_to edit_category_path(c) do %>
    <span class="icon is-small">
      <i class="fa fa fa-edit" aria-hidden="true"></i>
    </span>
    <% end %> 
    <%= link_to c, method: :delete, data: { confirm: 'Are you sure?' } do %>
    <span class="icon is-small">
      <i class="fa fa-trash-o" aria-hidden="true"></i>
    </span>
    <% end %>
    <% end %>
    </li>
    <% end %>
  </ul>

  <br/>

  <% if has_role?(:admin) %>
  <%= link_to 'New Category', new_category_path, class:'button is-success' %>
  <% end %>

</div>

app/views/discussions/edit.html.erb
<h1>Editing Discussion</h1>

<%= render 'form', discussion: @discussion %>

<%= link_to 'Show', @discussion %> |
<%= link_to 'Back', discussions_path %>

app/views/discussions/edit.html.haml
%h1 Editing Discussion
= render 'form', discussion: @discussion
= link_to 'Show', @discussion
|
= link_to 'Back', discussions_path

app/views/discussions/index.html.erb
<div class="columns">
  <div class="column is-8">
  <h3 class="title is-5 has-text-grey-light">Latest from <strong><%= Discussion.count %></strong> discussions</h3>
  <div class="tabs is-centered">
  <ul>
    <li class="is-active"><a>Latest</a></li>
    <li><%= link_to "Popular", popular_discussions_path%></li>
    <li><%= link_to "Most Upvoted", most_upvoted_discussions_path%></li>
  </ul>
</div>
  <%= render 'discussions/search_form' %>
  <%= render 'shared/discussions'%>
  <%= render 'sidebar' %>
</div>
<nav class="column is-8">
  <%= paginate @discussions %>
</nav>
<!-- <nav class="pagination" role="navigation" aria-label="pagination">
  <%= paginate @discussions %>
</nav> -->
<!-- <nav class="pagination-previous" role="navigation" aria-label="pagination">
  <%= link_to_previous_page @discussions, 'Previous Page' %>
</nav>

<nav class="pagination-next" role="navigation" aria-label="pagination">
<%= link_to_next_page @discussions, 'Next Page' %>
</nav> -->

<!-- <nav class="pagination" role="navigation" aria-label="pagination">
  <a class="pagination-previous">Previous</a>
  <a class="pagination-next">Next page</a>
  <ul class="pagination-list">
    <li>
      <a class="pagination-link" aria-label="Goto page 1">1</a>
    </li>
    <li>
      <span class="pagination-ellipsis">&hellip;</span>
    </li>
    <li>
      <a class="pagination-link" aria-label="Goto page 45">45</a>
    </li>
    <li>
      <a class="pagination-link is-current" aria-label="Page 46" aria-current="page">46</a>
    </li>
    <li>
      <a class="pagination-link" aria-label="Goto page 47">47</a>
    </li>
    <li>
      <span class="pagination-ellipsis">&hellip;</span>
    </li>
    <li>
      <a class="pagination-link" aria-label="Goto page 86">86</a>
    </li>
  </ul>
</nav> -->

app/views/discussions/index.html.haml
%p#notice= notice
%h1 Discussions
%table
  %thead
    %tr
      %th Left side
      %th Right side
      %th{colspan: "3"}
  %tbody
    - @discussions.each do |discussion|
      %tr
        %td= discussion.left_side
        %td= discussion.right_side
        %td= link_to 'Show', discussion
        %td= link_to 'Edit', edit_discussion_path(discussion)
        %td= link_to 'Destroy', discussion, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Discussion', new_discussion_path

app/views/discussions/most_upvoted.html.erb
<div class="columns">
  <div class="column is-8">
  <h3 class="title is-5 has-text-grey-light">Most upvoted from <strong><%= Discussion.count %></strong> discussions</h3>
  <div class="tabs is-centered">
  <ul>
    <li><%= link_to "Latest", discussions_path %></li>
    <li><%= link_to "Popular", popular_discussions_path%></li>
    <li class="is-active"><a>Most Upvoted</a></li>
  </ul>
</div>
  <%= render 'discussions/search_form' %>
  <%= render 'shared/discussions'%>
  <%= render 'sidebar' %>
</div>
<nav class="column is-8">
  <%= paginate @discussions %>
</nav>

app/views/discussions/new.html.erb
<h1 class="title">New Discussion</h1>
<br/>

<%= render 'form', discussion: @discussion %>

<br/>
<%= link_to 'Back', discussions_path %>

app/views/discussions/new.html.haml
%h1 New Discussion
= render 'form', discussion: @discussion
= link_to 'Back', discussions_path

app/views/discussions/popular.html.erb
<div class="columns">
  <div class="column is-8">
  <h3 class="title is-5 has-text-grey-light">Most popular from <strong><%= Discussion.count %></strong> discussions</h3>
  <div class="tabs is-centered">
  <ul>
    <li><%= link_to "Latest", discussions_path %></li>
    <li class="is-active"><a>Popular</a></li>
    <li><%= link_to "Most Upvoted", most_upvoted_discussions_path%></li>
  </ul>
</div>
  <%= render 'discussions/search_form' %>
  <%= render 'shared/discussions'%>
  <%= render 'sidebar' %>
</div>
<nav class="column is-8">
  <%= paginate @discussions %>
</nav>

app/views/discussions/show.html.erb
    <section class="hero">
    <div class="hero-body">
    <nav class="level is-mobile">
    <div class="level-item has-text-centered" id="head">
         <div class="control">
    <div class="tags has-addons">
      <span class="tag is-large"><%= link_to @discussion.left_side, { :controller => "discussions", :action => "vote", :side => "left" }, class: "title is-3 has-text-link", method: :post %></span>
      <span class="tag is-link is-large"><%= DiscussionsMembersWorker.count_users_by_side(@discussion.id, "left") %></span>
    </div>
  </div>
    </div>
    <div class="level-item has-text-centered">
      <div class="control">
        <span class="tag is-large has-background-grey"><h1 class="title is-3 has-text-white">VS</h1></span>
      </div>
    </div>
    <div class="level-item has-text-centered">
      <div class="control">
    <div class="tags has-addons">
      <span class="tag is-danger is-large"><%= DiscussionsMembersWorker.count_users_by_side(@discussion.id, "right") %></span>
      <span class="tag  is-large"><%= link_to @discussion.right_side, { :controller => "discussions", :action => "vote", :side => "right" }, class: "title is-3 has-text-danger", method: :post %></span>
    </div>
  </div>
      <div>
      </div>
    </div>
  </nav>
  </div>
</section>
    <div class="level">
      <div class="level-left">
        <div class="subtitle is-4 has-text-centered"><%= @discussion.question %></div>
      </div>
    </div>
    <div class="level">
      <div class="level-left">
        <h3 class="subtitle is-5 has-text-grey">created by <%= @discussion.user.username %> in <%= link_to @discussion.category.title, @discussion.category %></h3>
      </div>
      <div class="level-right">
        <div class="buttons">
          <% if DiscussionsMembersWorker.record_already_exist?(@discussion, current_user) %>
          <a class="button is-primary">
          <span class="open-modal" data-modal-id="#my-modal<%= @discussion.id %>">Leave argument</span>
          </span>
          </a>
        <% end %>
          <% if EditPolicy.discussion_can_be_edited?(@discussion, current_user) || has_role?(:admin) %>
            <%= link_to 'Edit Discussion', edit_discussion_path(@discussion), class:'button is-link'%>
            <%= link_to 'Delete', discussion_path(@discussion), method: :delete, data: { confirm: "Delete discussion?" }, class:'button is-danger' %>
        <% end %>
        </div>
      </div>
    </div>
    <hr />
    <nav class="level">
    <div class="level-item has-text-centered">
      <div>
        <p class="heading">Arguments</p>
        <p class="title"><%= @discussion.arguments.count %></p>
      </div>
    </div>
    <div class="level-item has-text-centered">
      <div>
        <p class="heading">Upvotes</p>
        <p class="title">
          <% if !VotesWorker.get_likes(@discussion.id, 'Discussion') %>
          <%= 0 %>
          <% else %>
          <%= VotesWorker.get_likes(@discussion.id, 'Discussion') %>
          <% end %>
          <%= link_to like_vote_path(item_id: @discussion.id, item_type: 'Discussion') do %>
            <span class="icon is-small">
              <i class="fa fa-arrow-up" aria-hidden="true"></i>
            </span>
          <% end %>
        </p>
      </div>
    </div>
    <div class="level-item has-text-centered">
      <div>
        <p class="heading">Downvotes</p>
        <p class="title">
          <% if !VotesWorker.get_dislikes(@discussion.id, 'Discussion') %>
          <%= 0 %>
          <% else %>
          <%= VotesWorker.get_dislikes(@discussion.id, 'Discussion') %>
          <% end %>
          <%= link_to dislike_vote_path(item_id: @discussion.id, item_type: 'Discussion') do %>
            <span class="icon is-small">
              <i class="fa fa-arrow-down" aria-hidden="true" style="color:red"></i>
            </span>
          <% end %>
        </p>
      </div>
    </div>
  </nav>
  <hr />
  <div class="columns">
  <div class="column is-half">
  <div id="discussion-replies">
     <% @discussion.arguments.each do |argument| %>
     <% if argument.user.side(@discussion.id) == 'left' %>
     <%= render argument %>
     <% end %>
     <% end %>
  </div>
  </div>
  <div class="column is-half">
	<div id="discussion-replies">
     <% @discussion.arguments.each do |argument| %>
     <% if argument.user.side(@discussion.id) == 'right' %>
     <%= render argument %>
     <% end %>
     <% end %>
	</div>
  </div>
  </div>
    <div id="bottom">
    <h3 class="subtitle is-3 has-text-grey">Leave a argument</h3>
    <% if user_signed_in? %>
     <% if DiscussionsMembersWorker.record_already_exist?(@discussion, current_user) %>
      <%= render 'arguments/form', argument: Argument.new, discussion: @discussion, user: current_user %>
    <% else %>
      <p >First you need to vote</p>
    <% end %>
    <% else %>
    <p>To leave argument you need to <%= link_to 'login', new_user_session_path %>. Don't have an account?
      <%= link_to 'Sign up', new_user_registration_path %> for one.</p>
    <% end %>
  </div>
    <div aria-hidden="" class="modal" id="my-modal<%= @discussion.id %>">
      <div class="modal-background close-modal" data-modal-id="#my-modal<%= @discussion.id %>"></div>
        <div class="modal-content">
         <% if user_signed_in? %>
         <% if DiscussionsMembersWorker.record_already_exist?(@discussion, current_user) %>
          <%= render 'arguments/form', argument: Argument.new, discussion: @discussion, user: current_user %>
        <% else %>
          <p >First you need to vote</p>
        <% end %>
        <% else %>
        <p>To leave argument you need to <%= link_to 'login', new_user_session_path %>. Don't have an account?
          <%= link_to 'Sign up', new_user_registration_path %> for one.</p>
        <% end %>
        </div>
        <button aria-label="close" class="delete close-modal" data-modal-id="#my-modal<%= @discussion.id %>"></button>
    </div>

app/views/discussions/show.html.haml
%p#notice= notice
%p
  %strong Left side:
  = @discussion.left_side
%p
  %strong Right side:
  = @discussion.right_side
= link_to 'Edit', edit_discussion_path(@discussion)
|
= link_to 'Back', discussions_path