config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'profile/show'
  resources :replies
  resources :categories
  resources :votes do
    member do
      get :like, to: 'votes#like', as: :like
      get :dislike, to: 'votes#dislike', as: :dislike
    end
  end
  resources :discussions do
    collection do
      get :search, to: 'discussions#search', as: :search
      get :popular, to: 'discussions#popular', as: :popular
      get :most_upvoted, to: 'discussions#most_upvoted', as: :most_upvoted
    end
    member do
      post :vote, to: 'discussions#vote'
      resources :arguments
    end
  end

  root 'discussions#index'
  devise_for :users
  resources :users
  get :user, to: 'users#profile', as: :profile
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :discussions
  resourcify

  validates :title, length: { in: 1..20 }
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[show]

  # GET /categories/1
  # GET /categories/1.json
  def show
    @discussions = Discussion.where('category_id = ?', @category.id)
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit; end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to root_path, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    redirect_to root_path, notice: 'You dont have permition!' unless current_user.has_role?(:admin)
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to root_path, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    redirect_to root_path, notice: 'You dont have permition!' unless current_user.has_role?(:admin)
    @category.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def category_params
    params.require(:category).permit(:title)
  end
end

app/helpers/categories_helper.rb
# frozen_string_literal: true

module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= simple_form_for(@category) do |f| %>
  <%= f.error_notification %>

 <div class="field">
   <div class="control">
     <%= f.input :title, input_html: { class: 'input' }, wrapper: false, label_html: { class: 'label' } %>
   </div>
 </div>

 <%= f.button :submit, class: 'button is-success is-active' %>
<% end %>

app/views/categories/_form.html.haml
= form_with(model: category, local: true) do |form|
  - if category.errors.any?
    #error_explanation
      %h2
        = pluralize(category.errors.count, "error")
        prohibited this category from being saved:
      %ul
<<<<<<< HEAD
        - category_.errors.full_messages.each do |message|
=======
        - category.errors.full_messages.each do |message|
>>>>>>> 60dc792aa515d82ba75d1d2717be8fc213dd43e7
          %li= message
  .field
    = form.label :title
    = form.text_field :title
  .actions
    = form.submit

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

app/views/categories/edit.html.haml
%h1 Editing Category
= render 'form', category: @category
= link_to 'Show', @category
|
= link_to 'Back', categories_path

app/views/categories/index.html.haml
%p#notice= notice
%h1 Categories
%table
  %thead
    %tr
      %th Title
      %th{colspan: "3"}
  %tbody
    - @categories.each do |category|
      %tr
        %td= category.title
        %td= link_to 'Show', category
        %td= link_to 'Edit', edit_category_path(category)
        %td= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Category', new_category_path

app/views/categories/new.html.erb
<h1 class="title">New Category</h1>
<br/>
<% if has_role?(:admin) %>
<%= render 'form', category: @category %>
<% else %>
 <p class="has text center">You don't have permission to create new category!</p>
<% end %>
<br/>

<%= link_to 'Back', discussions_path %>

app/views/categories/new.html.haml
%h1 New Category
= render 'form', category: @category
= link_to 'Back', categories_path

app/views/categories/show.html.erb
<div class="columns">
  <div class="column is-8">
  <h3 class="title is-5 has-text-grey-light">Discussions in category <%= @category.title %></h3>
  <%= render 'discussions/search_form' %>
  <%= render 'shared/discussions'%>
  <%= render 'discussions/sidebar' %>
</div>

app/views/categories/show.html.haml
%p#notice= notice
%p
  %strong Title:
  = @category.title
= link_to 'Edit', edit_category_path(@category)
|
= link_to 'Back', categories_path