config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'profile/show'
  resources :replies
  resources :categories
  resources :votes do
    member do
      get :like, to: 'votes#like', as: :like
      get :dislike, to: 'votes#dislike', as: :dislike
    end
  end
  resources :discussions do
    collection do
      get :search, to: 'discussions#search', as: :search
      get :popular, to: 'discussions#popular', as: :popular
      get :most_upvoted, to: 'discussions#most_upvoted', as: :most_upvoted
    end
    member do
      post :vote, to: 'discussions#vote'
      resources :arguments
    end
  end

  root 'discussions#index'
  devise_for :users
  resources :users
  get :user, to: 'users#profile', as: :profile
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
      can :manage, :all
    else
      can :read, :all
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/argument.rb
# frozen_string_literal: true

class Argument < ApplicationRecord
  belongs_to :user
  belongs_to :discussion
  has_many :replies, dependent: :destroy
  has_many :votes, as: :item

  validates :content, presence: true
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :discussions
  resourcify

  validates :title, length: { in: 1..20 }
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :discussion

  validates :content, presence: true
end

app/models/discussion.rb
# frozen_string_literal: true

class Discussion < ApplicationRecord
  belongs_to :category
  belongs_to :user
  has_many   :arguments, dependent: :destroy
  has_many :votes, as: :item

  validates :left_side, :right_side, presence: true
  validates :left_side, :right_side, length: { in: 1..80 }
  validates :question, length: { in: 0..120 }

  def self.side_inc(id, side)
    discussion = Discussion.find(id)
    discussion.increment!("#{side}_counter")
  end

  def self.search(search)
    if search
      where(['right_side LIKE ?', search]).or(Discussion.where(['left_side LIKE ?', search])).or(Discussion.where(['question LIKE ?', search]))
    else
      find(:all)
    end
  end
  resourcify
end

app/models/discussions_member.rb
# frozen_string_literal: true

class DiscussionsMember < ApplicationRecord
  belongs_to :discussion
  belongs_to :user
  has_many :discussions
  has_many :users

  ALLOWED_SIDES = %w[right left].freeze

  validates :side, inclusion: { in: ALLOWED_SIDES }
end

app/models/reply.rb
# frozen_string_literal: true

class Reply < ApplicationRecord
  belongs_to :argument
  belongs_to :user
  has_many :votes, as: :item

  validates :content, presence: true
end

app/models/role.rb
# frozen_string_literal: true

class Role < ApplicationRecord
  has_and_belongs_to_many :users, join_table: :users_roles

  belongs_to :resource,
             polymorphic: true,
             optional: true

  validates :resource_type,
            inclusion: { in: Rolify.resource_types },
            allow_nil: true

  scopify
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: %i[facebook]
  has_many :discussions
  has_many :arguments
  has_many :replies

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.username = auth.info.name   # assuming the user model has a name
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data == session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
        end
      end
    end


  attr_writer :login

  def login
    @login || username || email
  end

  def side(discussion_id)
    DiscussionsMembersWorker.get_users_side(discussion_id, id)
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    login = conditions.delete(:login)
    if login
      where(conditions.to_h).where(['lower(username) = :value OR lower(email) = :value', { value: login.downcase }])
                            .first
    elsif conditions.key?(:username) || conditions.key?(:email)
      where(conditions.to_h).first
    end
  end

  has_attached_file :avatar, styles: { medium: '300x300>', thumb: '100x100#' }, default_url: '/images/:style/missing.jpg'
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
  validates :username, length: { in: 3..12 }
end

app/models/vote.rb
# frozen_string_literal: true

class Vote < ApplicationRecord
  belongs_to :item, polymorphic: true
end

app/controllers/votes_controller.rb
# frozen_string_literal: true

class VotesController < ApplicationController
  before_action :set_discussion, only: %i[like dislike]
  before_action :authenticate_user!

  def like
    get_vote
    @vote.value += 1 unless @vote.value == 1
    @vote.save
    respond_to do |format|
      format.html { redirect_to @discussion }
    end
  end

  def dislike
    get_vote
    @vote.value -= 1 unless @vote.value == -1
    @vote.save
    respond_to do |format|
      format.html { redirect_to @discussion }
    end
  end

  private

  def get_vote
    current_item = get_item_by_type(params[:item_id], params[:item_type])
    @vote = current_item.votes.find_by_user_id(current_user.id)
    unless @vote
      @vote = Vote.create(user_id: current_user.id, value: 0)
      current_item.votes << @vote
    end
  end

  def get_item_by_type(id, type)
    case type
    when 'Argument'
      item = Argument.find(id)
    when 'Reply'
      item = Reply.find(id)
    when 'Discussion'
      item = Discussion.find(id)
    end
    item
  end

  def set_discussion
    @discussion = Discussion.find(params[:id])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  require 'redcarpet/render_strip'

  def has_role?(role)
    current_user&.has_role?(role)
  end
end

app/helpers/categories_helper.rb
# frozen_string_literal: true

module CategoriesHelper
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper
end

app/helpers/discussions_helper.rb
# frozen_string_literal: true

module DiscussionsHelper
  def discussion_author(discussion)
    user_signed_in? && current_user.id == discussion.user_id
  end

  def reply_author(reply)
    user_signed_in? && current_user.id == reply.user_id
  end
end

app/helpers/profile_helper.rb
# frozen_string_literal: true

module ProfileHelper
end

app/helpers/replies_helper.rb
# frozen_string_literal: true

module RepliesHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/helpers/votes_helper.rb
# frozen_string_literal: true

module VotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="has-navbar-fixed-top">
  <head>
    <title>Squabble</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'application' %>
    <%= stylesheet_link_tag    'application' %>
    <%= javascript_include_tag 'application' %>

  </head>

  <body>
    <% if flash[:notice] %>
      <div class="notification is-success global-notification">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>
    <% if flash[:alert] %>
    <div class="notification is-danger global-notification">
      <p class="alert"><%= alert %></p>
    </div>
    <% end %>
     <nav class="navbar is-primary is-fixed-top has-shadow" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <%= link_to root_path, class:"navbar-item" do %>
           <%= image_tag('/images/logo.png') %>
           &nbsp;
          <h1 class="title is-5 has-text-white discussion-title">Squabble</h1>
        <% end  %>
      <div class="navbar-burger burger" data-target="navbar">
        <span></span>
        <span></span>
        <span></span>
      </div>
    </div>

      <div id="navbar" class="navbar-menu">
        <div class="navbar-end">
          <% if user_signed_in? %>
          <div class="navbar-item">
            <div class="field is-grouped">
              <%= link_to 'New Discussion', new_discussion_path, class:"button is-success is-outlined" %>
            </div>
          </div>
          <div class="navbar-item has-dropdown is-hoverable">
            <%= link_to 'Account', profile_show_path, class: "navbar-link" %>
            <div class="navbar-dropdown is-right">
              <%= link_to current_user.username, profile_show_path, class:"navbar-item" %>
              <%= link_to "Log Out", destroy_user_session_path, method: :delete, class:"navbar-item" %>
            </div>
          </div>
         <% else %>
         <div class="navbar-item">
          <div class="field is-grouped">
            <p class="control">
              <%= link_to 'New Discussion', new_discussion_path, class:"button is-info" %>
            </p>

            <p class="control">
              <%= link_to "Sign In", new_user_session_path, class: "button is-light"%>
            </p>

            <p class="control">
              <%= link_to "Sign up", new_user_registration_path, class: "button is-light" %>
            </p>
          </div>
          </div>
          <% end %>
        </div>
    </div>
  </nav>

<section class="section">
  <div class="container">
    <%= yield %>

  </body>
</html>

app/views/layouts/application.html.haml
<<<<<<< HEAD
!!!
=======
>>>>>>> 60dc792aa515d82ba75d1d2717be8fc213dd43e7
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Discussions
    = csrf_meta_tags
    %meta{content: "width=device-width, initial-scale=1", name: "viewport"}/
    = stylesheet_link_tag 'application'
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %body
    - if flash[:notice]
      .notification.is-success.global-notification
        %p.notice= notice
    - if flash[:alert]
      .notification.is-danger.global-notification
        %p.alert= alert
<<<<<<< HEAD
    %nav.navbar.is-light{"aria-label" => "main navigation", role: "navigation"}
      .navbar-brand
        = link_to root_path, class:"menu_icon" do
          = image_tag("/assets/11.png", class: "menu_icon")
      .navbar-item
        - if user_signed_in?
          .navbar-item.has-dropdown.is-hoverable
          = link_to 'Profile', edit_user_registration_path, class: "navbar-link"
          .field.is-grouped
          = link_to 'Log out', destroy_user_session_path,method: :delete, class:"button"
        - else
          %navbar-item
            .field.is-grouped
              %p.control
                = link_to 'New Discussion', new_discussion_path, class:"button is-info"
              %p.control
                = link_to "Sign In", new_user_session_path, class: "button is-light"
              %p.control
                = link_to "Sign up", new_user_registration_path, class: "button is-light"
=======

  #navbar.navbar-menu
    %nav.navbar.is-light{"aria-label" => "main navigation", role: "navigation"}
    .navbar-brand
      = link_to root_path, class:"menu_icon" do
        = image_tag("/assets/11.png", class: "menu_icon")
    .navbar-brand
      = link_to root_path, class:"navbar-item" do
        = image_tag("/assets/11.png", class: "navbar-item")
    .navbar-end
      - if user_signed_in?
        .navbar-item
          .navbar-item.has-dropdown.is-hoverable
          = link_to 'Profile', edit_user_registration_path, class: "navbar-link"
          .navbar-dropdown.is-right
            = link_to current_user.username, edit_user_registration_path, class:"navbar-item"
            = link_to "Sign Out", cancel_user_registration_path, method: :delete, class:"navbar-item"
          .field.is-grouped
            = link_to 'Log out', destroy_user_session_path, class:"button"

      - else
        .navbar-item
          .field.is-grouped
            %p.control
              = link_to 'New Discussion', new_discussion_path, class:"button is-info"
            %p.control
              = link_to "Sign In", new_user_session_path, class: "button is-light"
            %p.control
              = link_to "Sign up", new_user_registration_path, class: "button is-light"
>>>>>>> 60dc792aa515d82ba75d1d2717be8fc213dd43e7
  %section.section
    .container
      = yield

app/views/shared/_discussions.html.erb
  </br>
  <div class="discussions">
    <% @discussions.each do |discussion| %>     
      <div class="columns bb-not-last pv10">
        <div class="column is-1">
            <%= image_tag(discussion.user.avatar.url(:thumb), class:'border-radius-50', size: 48, alt: discussion.user.username) %>
        </div>
        <div class="column is-8">
          <%= link_to discussion do %>
            <h3 class="title is-5 "><span class="has-text-link"><%= discussion.left_side %></span> <span class="has-text-grey">vs</span> <span class="has-text-danger"><%= discussion.right_side %></span></h3>
          <% end %>
          <div class="content">
            <%= truncate(discussion.question, length: 140) %>
            <p><em><small>Posted <%= time_ago_in_words(discussion.created_at) %> ago in
              <% if discussion.category %>
                <%= link_to discussion.category.title, discussion.category %>
              <% end %>
              by <%= discussion.user.username %>
              </small>
              </em>
            </p>
          </div>
        </div>

        <% if EditPolicy.discussion_can_be_edited?(discussion, current_user) || has_role?(:admin) %>
        <div class="column has-text-right">
          <%= link_to 'Edit', edit_discussion_path(discussion), class:'button is-link' %>
          <%= link_to 'Delete', discussion, method: :delete, data: { confirm: 'Are you sure?' }, class: "button is-danger" %>
        </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>